.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014-17  Chris Boot <debian@bootc.net>
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NRPE-NG.CFG 5 "2014-11-07" "nrpe-ng"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nrpe-ng.cfg \- configuration file for \fBnrpe-ng\fR
.SH SYNOPSIS
.B /etc/nagios/nrpe-ng.cfg
.SH DESCRIPTION
TODO
.SH FILES
.I /etc/nagios/nrpe-ng.cfg
.SH SEE ALSO
.BR nrpe-ng (1),
https://github.com/bootc/nrpe-ng
